mqtt:
  broker: your.mqtt.ip.address
  port: 1883
  client_id: home-assistant-1
  username: YOURUSERNAME
  password: YOURPASSWORD

light:
    - platform: mqtt
    schema: json
    name: "RGB Light Strip 1"
    state_topic: "home/RGBStrip1"
    command_topic: "home/RGBStrip1/set"
    rgb: true
    availability_topic: "home/RGBStrip1/LWT"
    white_value: true
    effect: true
    effect_list:
      - solid    
      - Music - L2R
      - Music - Middle
      - Music - Fma965
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple      
      - twinkle
      - sinelon
      - sine hue
      - full hue
      - breathe
      - hue breathe
      - Christmas
      - christmas alternate
      - random stars
      - St Patty
      - Valentine
      - Turkey Day
      - Thanksgiving
      - USA
      - Independence
      - Halloween
      - Go Lions
      - Hail
      - Touchdown
      - Punkin
      - Lovey Day
      - Holly Jolly      
    brightness: true
    optimistic: false
    qos: 0
